# -*- coding: utf-8 -*-
"""102303259

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPAEGNeZvY7BqCqtmcWkgPn5E_8vo3gv
"""

import sys
import os
import zipfile
from yt_dlp import YoutubeDL
from pydub import AudioSegment

def downloadAndProcess(singerName, numVideos, audioDuration, outputFileName):
    ydlOpts = {
        'format': 'bestaudio/best',
        'noplaylist': True,
        'quiet': True,
        'extract_audio': True,
        'audio_format': 'mp3',
        'outtmpl': 'temp_downloads/%(title)s.%(ext)s',
    }

    print(f"Searching and downloading {numVideos} videos of {singerName}...")

    with YoutubeDL(ydlOpts) as ydl:
        try:
            searchQuery = f"ytsearch{numVideos}:{singerName}"
            ydl.download([searchQuery])
        except Exception as e:
            print(f"Error downloading: {e}")
            sys.exit(1)

    print("Processing audios...")

    combinedAudio = AudioSegment.empty()
    files = os.listdir('temp_downloads')

    filesProcessed = 0
    for file in files:
        if file.endswith(".mp3"):
            filePath = os.path.join('temp_downloads', file)
            audio = AudioSegment.from_mp3(filePath)
            extractedAudio = audio[:audioDuration * 1000]
            combinedAudio += extractedAudio
            filesProcessed += 1
            if filesProcessed >= numVideos:
                break

    combinedAudio.export(outputFileName, format="mp3")
    print(f"Done! Saved as {outputFileName}")

    for file in os.listdir('temp_downloads'):
        os.remove(os.path.join('temp_downloads', file))
    os.rmdir('temp_downloads')

def main():
    if len(sys.argv) != 5:
        print("Usage: python <program.py> <SingerName> <NumberOfVideos> <AudioDuration> <OutputFileName>")
        sys.exit(1)

    singerName = sys.argv[1]

    try:
        numVideos = int(sys.argv[2])
        audioDuration = int(sys.argv[3])
    except ValueError:
        print("Number of videos and duration must be integers.")
        sys.exit(1)

    outputFileName = sys.argv[4]

    if numVideos <= 10:
        print("Number of videos must be greater than 10")
        sys.exit(1)

    if audioDuration <= 20:
        print("Audio duration must be greater than 20 seconds")
        sys.exit(1)

    if not os.path.exists('temp_downloads'):
        os.makedirs('temp_downloads')

    downloadAndProcess(singerName, numVideos, audioDuration, outputFileName)

if __name__ == "__main__":
    main()
